// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type DiscountTypeEnum string

const (
	DiscountTypeEnumNominal    DiscountTypeEnum = "nominal"
	DiscountTypeEnumPercentage DiscountTypeEnum = "percentage"
)

func (e *DiscountTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscountTypeEnum(s)
	case string:
		*e = DiscountTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscountTypeEnum: %T", src)
	}
	return nil
}

type NullDiscountTypeEnum struct {
	DiscountTypeEnum DiscountTypeEnum `json:"discount_type_enum"`
	Valid            bool             `json:"valid"` // Valid is true if DiscountTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscountTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DiscountTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscountTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscountTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscountTypeEnum), nil
}

type StockTypeEnum string

const (
	StockTypeEnumIN  StockTypeEnum = "IN"
	StockTypeEnumOUT StockTypeEnum = "OUT"
)

func (e *StockTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockTypeEnum(s)
	case string:
		*e = StockTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for StockTypeEnum: %T", src)
	}
	return nil
}

type NullStockTypeEnum struct {
	StockTypeEnum StockTypeEnum `json:"stock_type_enum"`
	Valid         bool          `json:"valid"` // Valid is true if StockTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.StockTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockTypeEnum), nil
}

type AppKey struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Key  string `json:"key"`
}

type AuthToken struct {
	ID                  int64          `json:"id"`
	Name                string         `json:"name"`
	DeviceID            string         `json:"device_id"`
	DeviceType          string         `json:"device_type"`
	Token               string         `json:"token"`
	TokenExpired        time.Time      `json:"token_expired"`
	RefreshToken        string         `json:"refresh_token"`
	RefreshTokenExpired time.Time      `json:"refresh_token_expired"`
	IsLogin             bool           `json:"is_login"`
	UserLogin           sql.NullString `json:"user_login"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
}

type Config struct {
	ID          int64          `json:"id"`
	Key         string         `json:"key"`
	Description sql.NullString `json:"description"`
	Value       string         `json:"value"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
}

type Employee struct {
	ID                     int64          `json:"id"`
	Guid                   string         `json:"guid"`
	Name                   sql.NullString `json:"name"`
	ProfilePictureImageUrl sql.NullString `json:"profile_picture_image_url"`
	Phone                  string         `json:"phone"`
	Email                  string         `json:"email"`
	RoleID                 int32          `json:"role_id"`
	IsActive               sql.NullBool   `json:"is_active"`
	CreatedAt              time.Time      `json:"created_at"`
	CreatedBy              string         `json:"created_by"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	UpdatedBy              sql.NullString `json:"updated_by"`
	DeletedAt              sql.NullTime   `json:"deleted_at"`
	DeletedBy              sql.NullString `json:"deleted_by"`
	LastLogin              sql.NullTime   `json:"last_login"`
}

type Product struct {
	ID                int64          `json:"id"`
	Guid              string         `json:"guid"`
	Name              sql.NullString `json:"name"`
	ProductPictureUrl sql.NullString `json:"product_picture_url"`
	Description       string         `json:"description"`
	CreatedAt         time.Time      `json:"created_at"`
	CreatedBy         string         `json:"created_by"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	UpdatedBy         sql.NullString `json:"updated_by"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	DeletedBy         sql.NullString `json:"deleted_by"`
	ProductCode       string         `json:"product_code"`
	CategoryID        string         `json:"category_id"`
	ProductSku        string         `json:"product_sku"`
	IsVariant         bool           `json:"is_variant"`
}

type ProductCategory struct {
	ID        int64          `json:"id"`
	Guid      string         `json:"guid"`
	Name      string         `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
	CreatedBy string         `json:"created_by"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	UpdatedBy sql.NullString `json:"updated_by"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	DeletedBy sql.NullString `json:"deleted_by"`
}

type ProductPrice struct {
	ID               int64                `json:"id"`
	Guid             string               `json:"guid"`
	ProductID        sql.NullString       `json:"product_id"`
	ProductVariantID sql.NullString       `json:"product_variant_id"`
	Price            int64                `json:"price"`
	DiscountType     NullDiscountTypeEnum `json:"discount_type"`
	Discount         sql.NullInt64        `json:"discount"`
	IsActive         bool                 `json:"is_active"`
	IsActiveBy       sql.NullString       `json:"is_active_by"`
	CreatedAt        time.Time            `json:"created_at"`
	CreatedBy        string               `json:"created_by"`
	UpdatedAt        sql.NullTime         `json:"updated_at"`
	UpdatedBy        sql.NullString       `json:"updated_by"`
	DeletedAt        sql.NullTime         `json:"deleted_at"`
	DeletedBy        sql.NullString       `json:"deleted_by"`
}

type ProductVariant struct {
	ID         int64          `json:"id"`
	Guid       string         `json:"guid"`
	ProductID  string         `json:"product_id"`
	Name       string         `json:"name"`
	Sku        string         `json:"sku"`
	IsActive   bool           `json:"is_active"`
	IsActiveBy sql.NullString `json:"is_active_by"`
	CreatedAt  time.Time      `json:"created_at"`
	CreatedBy  string         `json:"created_by"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	UpdatedBy  sql.NullString `json:"updated_by"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	DeletedBy  sql.NullString `json:"deleted_by"`
}

type ProductsHistory struct {
	ID            int64          `json:"id"`
	Guid          string         `json:"guid"`
	ProductGuid   string         `json:"product_guid"`
	Quantity      int64          `json:"quantity"`
	WarehouseGuid string         `json:"warehouse_guid"`
	TglMasuk      time.Time      `json:"tgl_masuk"`
	PegawaiMasuk  string         `json:"pegawai_masuk"`
	TglKeluar     time.Time      `json:"tgl_keluar"`
	PegawaiKeluar string         `json:"pegawai_keluar"`
	CreatedAt     time.Time      `json:"created_at"`
	CreatedBy     string         `json:"created_by"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	DeletedBy     sql.NullString `json:"deleted_by"`
}

type Stock struct {
	ID               int64          `json:"id"`
	Guid             string         `json:"guid"`
	ProductID        sql.NullString `json:"product_id"`
	ProductVariantID sql.NullString `json:"product_variant_id"`
	Stock            int64          `json:"stock"`
	CreatedAt        time.Time      `json:"created_at"`
	CreatedBy        string         `json:"created_by"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	UpdatedBy        sql.NullString `json:"updated_by"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	DeletedBy        sql.NullString `json:"deleted_by"`
}

type StockLog struct {
	ID               int64             `json:"id"`
	Guid             string            `json:"guid"`
	StockID          sql.NullString    `json:"stock_id"`
	ProductID        sql.NullString    `json:"product_id"`
	ProductVariantID sql.NullString    `json:"product_variant_id"`
	StockLog         int32             `json:"stock_log"`
	StockType        NullStockTypeEnum `json:"stock_type"`
	Note             sql.NullString    `json:"note"`
	CreatedAt        time.Time         `json:"created_at"`
	CreatedBy        string            `json:"created_by"`
	UpdatedAt        sql.NullTime      `json:"updated_at"`
	UpdatedBy        sql.NullString    `json:"updated_by"`
	DeletedAt        sql.NullTime      `json:"deleted_at"`
	DeletedBy        sql.NullString    `json:"deleted_by"`
}

type UserBackoffice struct {
	ID                     int64          `json:"id"`
	Guid                   string         `json:"guid"`
	Name                   sql.NullString `json:"name"`
	ProfilePictureImageUrl sql.NullString `json:"profile_picture_image_url"`
	Phone                  string         `json:"phone"`
	Email                  string         `json:"email"`
	RoleID                 int32          `json:"role_id"`
	Password               string         `json:"password"`
	Salt                   string         `json:"salt"`
	IsActive               sql.NullBool   `json:"is_active"`
	CreatedAt              time.Time      `json:"created_at"`
	CreatedBy              string         `json:"created_by"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	UpdatedBy              sql.NullString `json:"updated_by"`
	DeletedAt              sql.NullTime   `json:"deleted_at"`
	DeletedBy              sql.NullString `json:"deleted_by"`
	LastLogin              sql.NullTime   `json:"last_login"`
}

type UserBackofficeRole struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Access      sql.NullString `json:"access"`
	IsAllAccess sql.NullBool   `json:"is_all_access"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   string         `json:"created_by"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	DeletedBy   sql.NullString `json:"deleted_by"`
}

type UserHandheld struct {
	ID                     int64          `json:"id"`
	Guid                   string         `json:"guid"`
	Name                   string         `json:"name"`
	ProfilePictureImageUrl sql.NullString `json:"profile_picture_image_url"`
	Phone                  sql.NullString `json:"phone"`
	Email                  string         `json:"email"`
	Gender                 string         `json:"gender"`
	Address                sql.NullString `json:"address"`
	Salt                   string         `json:"salt"`
	Password               string         `json:"password"`
	IsActive               sql.NullBool   `json:"is_active"`
	FcmToken               sql.NullString `json:"fcm_token"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	DeletedAt              sql.NullTime   `json:"deleted_at"`
	LastLogin              sql.NullTime   `json:"last_login"`
}

type Warehouse struct {
	ID            int64          `json:"id"`
	Guid          string         `json:"guid"`
	WarehouseCode string         `json:"warehouse_code"`
	Name          sql.NullString `json:"name"`
	Address       string         `json:"address"`
	PhoneNumber   string         `json:"phone_number"`
	CreatedAt     time.Time      `json:"created_at"`
	CreatedBy     string         `json:"created_by"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	DeletedBy     sql.NullString `json:"deleted_by"`
}
